name: Nuget

on:
  push:
    branches: [ "nuget" ]
  pull_request:
    branches: [ "nuget" ]

jobs:
  build:
    
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'Local.SemanticKernel.sln'
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup NuGet
        uses: nuget/setup-nuget@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Pack
        run: dotnet pack --configuration $BUILD_CONFIG

      - name: Publish
        run: dotnet nuget push **\*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_APIKEY}}